---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: postgres-dns
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: postgres.lumu.au
      recordTTL: 300
      recordType: A
      targets:
        - 10.88.0.47
    - dnsName: postgres.lumu.au
      recordTTL: 300
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::47
