---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./notifications.yaml
  - ./coredns/ks.yaml
  - ./cilium/ks.yaml
  - ./descheduler/ks.yaml
  - ./fstrim/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  # - ./spegel/ks.yaml
