---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: alertmanager-internal
  namespace: networking
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: "alertmanager.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - 10.88.0.22
    - dnsName: "alertmanager.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::22