---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: minio-internal
  namespace: networking
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: "minio.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - ${INTERNAL_IP}
    - dnsName: "minio.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::22
    - dnsName: "s3.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - ${INTERNAL_IP}
    - dnsName: "s3.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::22
