---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  # - ./externalsecret.yaml
  - ./resourceclaimtemplate.yaml
  - ./helmrelease.yaml
patches:
  - path: volsync-patch.yaml
    target:
      kind: ReplicationSource
      name: dispatcharr
