---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gatus-internal
  namespace: networking
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: "status.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - 10.88.0.21
    - dnsName: "status.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::21
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gatus-external
  namespace: networking
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: "status.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - ${EXTERNAL_IP}
    - dnsName: "status.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::21
