---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autopulse-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTOPULSE__AUTH__USERNAME: "{{ .AUTOPULSE_USERNAME }}"
        AUTOPULSE__AUTH__PASSWORD: "{{ .AUTOPULSE_PASSWORD }}"
        AUTOPULSE__TARGETS__PLEX__TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: autopulse
    - extract:
        key: plex-token
      rewrite:
        - regexp:
            source: "token"
            target: "PLEX_TOKEN"
