---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hugo/ks.yaml
  - ./sonarr-kids/ks.yaml
  - ./actual/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-kids/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./changedetection/ks.yaml
  - ./esphome/ks.yaml
  - ./jellyseerr-plex/ks.yaml
  - ./mealie/ks.yaml
  - ./pinchflat/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./tautulli/ks.yaml
  - ./unpackerr/ks.yaml
