---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./media-pvc.yaml
  - ./hugo/ks.yaml
  - ./sonarr-kids/ks.yaml
  - ./actual/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-kids/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./changedetection/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./esphome/ks.yaml
  - ./jellyseerr-plex/ks.yaml
  - ./mealie/ks.yaml
  - ./pinchflat/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./tqm/ks.yaml
  - ./tautulli/ks.yaml
  - ./unpackerr/ks.yaml
  # - ./cross-seed/ks.yaml
  # - ./home-assistant/ks.yaml
  # - ./jellyfin/ks.yaml
  # - ./jellyplex-watched/ks.yaml
  # - ./jellyseerr/ks.yaml
  # - ./scrypted/ks.yaml
  # - ./valheim/ks.yaml
