apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mqzGjDlzKdapX7knzVJ/viJm,iv:QEJLCNom+sP51i908m6mzXQqZ8mFuvsJPJvO74PbxvM=,tag:K43hV3c1bGfCptsYKZHIPA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Dng7v3RK2jYWe0MMHFDdsu4ltrq0ehcTKT3MeOpjo+pY/a6A,iv:DRGW5aC4sxhwleSnwo8IfCBNNkqbaTp272xHfwRam5g=,tag:QSowF4HVDHvZ/xc9/Mp4Qw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BSrgD6PdhA==,iv:7d1sF/hYSxXTZw/VKdEqROyedgw26J9H7W4N2zR+7mY=,tag:1RggtzWoJefNlGW38YP1tw==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:6nmAmkGzcnf18EkSQg==,iv:Z5347+klsQoyd4EJ6FdOfp13ff0+eYA6/9C02EGuvtc=,tag:mVpJJFuHJQXnHgzXgzO6iA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:vuxMeWxrPBwmB1bA03qnqGVOt6Z2+WaIOlzVusmx8Oo=,iv:G4r9ABHvACGWm5zTVIJAZIJlMyVb1r2iT3rrYba7b+Q=,tag:Rl1RCPhZiLxQbjzmu+Elfg==,type:str]
    SECRET_PLEX_USER: ENC[AES256_GCM,data:A1q/4Wp/kA==,iv:p5CW/FqaUnBJfYwChP93ayc2WkuQkhCncQ2JMvwB5KY=,tag:bEa+3PROi7+TXMNOcJyIlA==,type:str]
    SECRET_JELLYFIN_USER: ENC[AES256_GCM,data:46hD4g==,iv:oPvgIJkq3NlJ7G9Zc74QDqPofcRAI8XRHibblTuKYUE=,tag:tgEAVxiDpmV7nsbmGjSJLg==,type:str]
    SECRET_PLEX_TOKEN: ENC[AES256_GCM,data:f7LJJHPrX82nBNxIahFftrOMB8o=,iv:NG3cawavqq2a7KeBryx3F+HFt9bQgmRu3wiZo2yTG0A=,tag:YRb82myhvRcLbirWpTZyrQ==,type:str]
    SECRET_JELLYFIN_TOKEN: ENC[AES256_GCM,data:XlSfC7lfyrk+r9eemtOMHzQVsLfONYvB/+Dnj2HTvwE=,iv:goJenAfp7H7hN6r8NSJ7KdJntm/Vqbetg4negoTpBI0=,tag:taHadzc5RHQwbxAGx+1rHw==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:aJW/Msp0SHAPW84oVyjJ,iv:I1lz0hNZgAzqL8N8lLgQbfz1176I4+M1rU3QFnAdr8A=,tag:UGNsliQV6zOhCkYTd/RI0A==,type:str]
    MINIO_TOKEN: ENC[AES256_GCM,data:lFUK5fxadJ0IpKINA3ij6mYmUNf9g0Cok5U6TCk=,iv:XAxx+7bj6mz2F4Iunx7M5FTNPLp+g9GDRfgbJv8s94U=,tag:clrHScZ3DUQN7ap655W2jg==,type:str]
    NAS_IP: ENC[AES256_GCM,data:N4r4AquN60bwRQ==,iv:pipsYhXpSPuOmTCCrZ5tN7eYoBNEiJibBSxjbaX4SJg=,tag:rRzO1PNfaI9t8edw3MnKBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eDNrS1BLUms1Qkc2MTU2
            ME9CNnowVUNsWVN3L1RoUnpWTWZoOVZBUlU0Clk1M2trazJGZzYrZUNTZzEwWVBI
            aEVqbmlBMmhNL1B4cjU1bjVneDRBK0kKLS0tIGRuSFlKbXVORmlqRS9nR09OQktC
            M3NBbC93U1p0T2x6dEQ4b3dzZU9PWTQKQtFj903oQzFLGXpoQ2oY8fUPsO4tdkCL
            aYTeyUlCNPT/eDOPkmGMgExY6+oYGcOFa3I/4ieKmjOrHht1aU6Qgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-07T05:04:07Z"
    mac: ENC[AES256_GCM,data:OaOuqtX12YJBo1c/8zfPLxClY/WzxTvWs/R4Bq2ajQNJqjkQHQyimiY7zCxVHgOukJSiWbP+q0JzrfDk/VQVPvT62YJ+u6J/+KnC08ewyAxjBXJ2+f/PyksatPZm4n/IMgcJBNR9u0edKHV9XRnghIPF/sOIuor2oWukH1FgTu4=,iv:hsP9x4I69O5AJmKDmB311Y4A7tjaHC+HVWtKEsM8hEQ=,tag:eJBdbJmEayW+m6wlGuL52g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
