---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../../templates/gatus/guarded
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
# configMapGenerator:
#   - name: lidarr-configmap
#     files:
#       - pushover-notify.sh=./resources/pushover-notify.sh
# generatorOptions:
#   disableNameSuffixHash: true
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
