---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hugo-root-external
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: lumu.au
      recordTTL: 300
      recordType: A
      targets:
        - ${EXTERNAL_IP}
    - dnsName: lumu.au
      recordTTL: 300
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::21
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hugo-root-internal
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: lumu.au
      recordTTL: 300
      recordType: A
      targets:
        - 10.88.0.21
    - dnsName: lumu.au
      recordTTL: 300
      recordType: AAAA
      targets:
        - 2402:21a0:2043:88::21
