apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EMQX_POSTGRES_PASS: ENC[AES256_GCM,data:Ab/X8S8EKHtLnz6FnPRtLczAo/Ktz6iV/x6F68e+heM=,iv:lkfvt3ExE5hX86NCZcmWd51An9/VZ5uNoBtTM+A4m7s=,tag:+wJQeOSd3cRcRK/uQugwOQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sMWVZxwd7DSjJL5BNkz97Ko3,iv:rgx5FVECYS1EPQpP/ZXg2UmCbTg6mcemY8UN6NP9TDA=,tag:U5Whl+NT/etNUTHWyBntEw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:M5oWHZZy2R8JoFShaDB2J+tkEEJBxeAzZuEjPC97gRO6Q2US,iv:1D5unQfMnMg0ujeygYneSujSReD5I1SowVbTR7sTlqw=,tag:viPjgvwDgCYHZH1mKjXSMg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:uGGshcn4WA==,iv:rbqAMPyOe9p5+aNpPwR3gpCTxB48ChLwVXTE66+/xps=,tag:PdW/t28CVNzAuofUCBPKtg==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:3FEzE6/UsmicLlq+YA==,iv:DX6C/BBfqRWnZMDbjWFjaIbH+0wR1pQ92gNTelML71s=,tag:bWOlzPFQ7gFaD4MCMiXQkQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:nItfCvLbA+tLABfHgV0EdtvW5FOf5r9j1Ni+0qagkuM=,iv:8gjc0iBJ4euNCMm6ipr2vQU+YRm1hCoLZF9Nk4V8skc=,tag:YnUZDLpOqIW9VW2B33uiWw==,type:str]
    SECRET_PLEX_USER: ENC[AES256_GCM,data:sec86GTrmw==,iv:55Wu/gBoHuhEmZT5D4Df6lpwl3msamfQba/1XHnrKpg=,tag:sfPLhJ2+rBhuvTGXlEzVEw==,type:str]
    SECRET_JELLYFIN_USER: ENC[AES256_GCM,data:wEeIrw==,iv:iu03Tw43E5LJZpZcK7LKQrq47psW+CeILGOhNdJCoBg=,tag:EJORMj8n3glQXfCAvkCNYg==,type:str]
    SECRET_PLEX_TOKEN: ENC[AES256_GCM,data:A/mxSizwRAgp22BYb5DYUdLZ4GE=,iv:jh2Ujz3dMm65GKjj4Kn90yXa6hm678b2qu1IKfAd0Dc=,tag:lbpgeZZg9UV1lpu3X4MDWw==,type:str]
    SECRET_JELLYFIN_TOKEN: ENC[AES256_GCM,data:7mVAC9yFYFgyWwkPHrSENBSmNiNgJEUtnx0lXLIPWxM=,iv:/ZBu8RE4V41gO18BwQqT9w7eXT1MxJz14we3gCdRTQw=,tag:ioZtznnKOBp9CmTGRzQZCQ==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:kHK2Z2oqfzJNkDoO3Y4X,iv:2PZ/R/189peBf1ePIe8Q56I68rrJE5qFBDxqWY93sTE=,tag:AkQb4ALFxSQYNDMHwnHD1Q==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:9T7FH2qoW8QV0ERlIlcH,iv:g3Azc8ntcSBYXEWleYcBkgUJmt47kg0K9haKBrPreJQ=,tag:FJKdayPgcLmq2fg5Mzx6vQ==,type:str]
    MINIO_TOKEN: ENC[AES256_GCM,data:XNxOOb3aAFS0di8Xw1eWXA6Ca9boTSJBiPGa4Mc=,iv:mxYAJp9HZOjOXAJi7wkmRvCuRHxrtMSTa/BvJBIyY4o=,tag:buhWY+LiKSSFoSkYTt3p+A==,type:str]
    NAS_IP: ENC[AES256_GCM,data:gPs0w7abXqlIrw==,iv:prWFuWA5ghEjGlVoHUV1EW6MPD4mf/vpqX5iuo3NBFM=,tag:fVVpPr0LrKisA4qlxaEqhg==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:3iz3LDNCx1ZJqa16Hg==,iv:JTAtlpiDafv+RdulyVM5YAvU+eYse2RnaHunOoN9WIg=,tag:cVOnJ5ELdpom33L62XX61Q==,type:str]
    INTERNAL_IP: ENC[AES256_GCM,data:AZwk0R4FzgCqjw==,iv:av5mnBvAB2c8jc9KRD36fQhUW3ZI4wrOjl63TAZRxvY=,tag:QNZegL6h888g7j9P/5w7JQ==,type:str]
sops:
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWnZYUDZmWVhJMWdEYkhJ
            cXUraDZtS2s0RDVxdmlMMFFHa1ZnVk9ac1ZvCjBDbVFkZkMwa2d6UVJoa1RCU1l1
            UklGYld1aGFCU2RUTXZDbnQ5bmsxejQKLS0tIEduM1p2VWZpWnFGWTZKRmZXbjBR
            VzJrOXZlMHA1UDlYWXlzS3RrTFoxak0Kbw02j8SZEfhleHkbkmD3DjbZ8tOjliUg
            m2JjQUW/jFaTpp+rfDedxwK3dsNREchs9wnN1ABS+p0QBn/MkFnzAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T16:02:48Z"
    mac: ENC[AES256_GCM,data:jODki9Zx8JAs8KiMOj9+zThqwRpRvuXyxRDWXgUVaRoT2xIfyYLztM9+OqIdbedC2815UgHCtlXzWr8TS+Ia2wLz7z8R2AnkgYpIsYWjgiLA3Fafttarg43Tv3M4BudL1F1Ra5NhhQ5kCXeFAo1TY0VXVWAcD5MsqRWAzhdLck4=,iv:VahC5Q1YiCUnTpm82nuqdgbAnJJEtLVn8nsPj2VQwVw=,tag:n+VKWKwQpKdBXez9TMuJHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
