---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${APP}-external
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: ${GATUS_SUBDOMAIN:-${APP}}.lumu.au
      recordTTL: 300
      recordType: A
      targets:
        - ${EXTERNAL_IP}
    - dnsName: ${GATUS_SUBDOMAIN:-${APP}}.lumu.au
      recordTTL: 300
      recordType: AAAA
      targets:
        - ${EXTERNAL_IP_AAAA}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${APP}-internal
  namespace: networking
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: "${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - 10.88.0.21
    - dnsName: "${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - ${EXTERNAL_IP_AAAA}
