---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  # - name: apc-ups-dashboard
  #   files:
  #     - apc-ups-dashboard.json=./resources/dashboard.json
  #   options:
  #     labels:
  #       grafana_dashboard: "true"
  # - name: apc-ups-dashboard1
  #   files:
  #     - 15735_rev2.json=./resources/15735_rev2.json
  #   options:
  #     labels:
  #       grafana_dashboard: "true"
  - name: apc-ups-snmp-configmap
    files:
      - snmp.yaml=./resources/snmp.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
