---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: plex-ipv4
spec:
  endpoints:
    - ip:
        address: 10.88.0.32
        port: 32400
