---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumu-production-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lumu-production-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.lumu.au,lumu.au"
          cert-manager.io/certificate-name: lumu-production
          cert-manager.io/common-name: lumu.au
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-production
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - extract:
        key: lumu-au-tls
        decodingStrategy: Base64
