---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumu-production-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lumu-production-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tls_crt | base64decode }}"
        tls.key: "{{ .tls_key | base64decode }}"
  data:
    - secretKey: tls_crt
      remoteRef:
        key: lumu-au-tls
        property: tls.crt
    - secretKey: tls_key
      remoteRef:
        key: lumu-au-tls
        property: tls.key
