---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mail-private
  namespace: networking
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: "mail.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - "10.1.2.25"
    - dnsName: "backup.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - "43.224.182.200"
    - dnsName: "backup.${SECRET_DOMAIN}"
      recordType: AAAA
      targets:
        - "2404:9400:2:0:216:3eff:fee6:786d"
