apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: instance-65002
      localASN: 65001
      peers:
        - name: peer-65001-mikrotik-v4
          peerASN: 65001
          peerAddress: 10.88.0.1
          peerConfigRef:
            name: cilium-peer-v4
        - name: peer-65001-mikrotik-v6
          peerASN: 65001
          peerAddress: 2402:21a0:2043:88::
          peerConfigRef:
            name: cilium-peer-v6
